'use strict';
const $=id=>document.getElementById(id);
const keys=['strikeouts','touchdowns','receptions'];
const specs={strikeouts:{title:'Strikeouts',basis:'Ranked by floor · MLB today',note:'Floor ranking uses recent 4+ and 5+ strikeout hit rates, with 6+ as the tie-breaker. Proj is a separate estimate. News and leash flags are advisory; projections do not adjust for news. ? means news unavailable.'},touchdowns:{title:'Touchdowns',basis:'Ranked by scoring probability · NFL',note:'TD% is the model’s probability of at least one touchdown. Fair is the model’s American odds, not a sportsbook quote. QB probabilities cover rushing touchdowns only. Weekly columns show touchdowns; – means did not play. TD10 counts scoring games in the last 10.'},receptions:{title:'Receptions',basis:'Ranked by floor · NFL',note:'Floor ranking uses recent 3+ and 4+ reception hit rates, then 5+ and projection. Q = questionable; NEWTEAM = history from a different offense; UP/DOWN = a change in recent targets.'}};
let active='strikeouts',payload=null;
const fmt=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function centralParts(date){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(p=>[p.type,p.value]));}
function isStale(category){if(category.status==='error')return true;const date=new Date(category.generatedAt);if(!category.generatedAt||!Number.isFinite(date.getTime()))return true;const p=centralParts(new Date());const day=`${p.year}-${p.month}-${p.day}`;let expected=new Date(day+'T12:00:00Z');if(Number(p.hour)*60+Number(p.minute)<450)expected.setUTCDate(expected.getUTCDate()-1);const expectedDay=expected.toISOString().slice(0,10);const g=centralParts(date);return `${g.year}-${g.month}-${g.day}`<expectedDay;}
function add(parent,tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;parent.append(el);return el;}
function value(column,v){if(v===null||v===undefined||v==='')return '—';if(/^p[3456]$/.test(column))return `${v}%`;if(column==='Fair'&&Number(v)>0)return `+${v}`;return String(v);}
function render(){const spec=specs[active],c=payload?.categories?.[active];$('panel').setAttribute('aria-labelledby','tab-'+active);$('title').textContent=spec.title;$('basis').textContent=spec.basis.toUpperCase();$('explanation').textContent=spec.note;$('slate').textContent=c?.slate||'';const rows=(c?.rows||[]).slice(0,10);$('count').textContent=`${rows.length} PLAYERS`;$('board').replaceChildren();const stale=c&&isStale(c);$('notice').hidden=!stale;$('notice').textContent=c?.status==='error'?c.message:'This board is overdue for an update. Check the last successful update time below.';const generated=c?.generatedAt?new Date(c.generatedAt):null;$('updated').textContent=generated&&Number.isFinite(generated.getTime())?`Last updated ${fmt.format(generated)} CT${stale?' · STALE':''}`:'No successful update yet';
if(!rows.length){add($('board'),'div',c?.message||'Loading rankings…','empty');return;}
const identity=active==='strikeouts'?'Pitcher':'Player';const cols=[identity,...(c.columns||[]).filter(k=>k!==identity)];const table=add($('board'),'table','');table.setAttribute('aria-label',`${spec.title} top 10`);const head=add(add(table,'thead',''),'tr','');add(head,'th','#').scope='col';cols.forEach(k=>{const th=add(head,'th',k);th.scope='col';});const body=add(table,'tbody','');
rows.forEach((row,i)=>{const tr=add(body,'tr','');add(tr,'td',String(i+1).padStart(2,'0'),'rank');cols.forEach(k=>{const td=add(tr,'td','');if(k===identity){add(td,'div',row[k]||'—','player');if(row.Tm||row.Pos)add(td,'div',[row.Tm,row.Pos].filter(Boolean).join(' · '),'sub');const parts=[];if(row.L10)parts.push('Last 10: '+row.L10);if(row.NewsHeadline)parts.push(row.NewsHeadline);if(parts.length){const d=add(td,'details','');add(d,'summary','Recent results & notes');parts.forEach(t=>add(d,'p',t));}}else{td.textContent=value(k,row[k]);if(['Proj','TD%'].includes(k))td.className='primary';if(['News','Leash','Inj','Role','Flags'].includes(k)&&row[k])td.className='flag';}});});}
function select(key){active=key;document.querySelectorAll('[role=tab]').forEach(b=>{const yes=b.dataset.key===key;b.setAttribute('aria-selected',String(yes));b.tabIndex=yes?0:-1;});render();}
document.querySelectorAll('[role=tab]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.key)));
document.querySelector('nav').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=e.key==='Home'?0:e.key==='End'?2:(keys.indexOf(active)+(e.key==='ArrowRight'?1:2))%3;select(keys[n]);$('tab-'+keys[n]).focus();});
async function load(){try{const response=await fetch('./data/latest.json',{cache:'no-store'});if(!response.ok)throw Error('Unavailable');const next=await response.json();if(next.schemaVersion!==1||!next.categories)throw Error('Invalid data');payload=next;}catch(e){if(!payload)payload={categories:Object.fromEntries(keys.map(k=>[k,{status:'error',rows:[],message:'The board could not be loaded. Please try again shortly.'}]))};else for(const c of Object.values(payload.categories)){c.status='error';c.message='Could not check for updates. Showing the last loaded results.';}}render();}
$('today').textContent=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',weekday:'short',month:'short',day:'numeric'}).format(new Date());load();setInterval(load,300000);setInterval(render,60000);
